feature/footer
MaksoN03/team-project pull request #6
Opened 2022-10-08 13:44 UTC by albinayevtushenko

add new HTML file

2022-10-08 20:23 UTC, MaksoN03 requested changes
Прохання виправити BEM-класифікування згідно з коментарями

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +    <h2 class="page-footer_title">Homemade ice cream made</h2>
Потрібно уточнити

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +    <h2 class="page-footer_title">Homemade ice cream made</h2>
Класи по BEM між блоком та елементом подвійне нижнє підкреслювання: page-footer__title. Звернути на це увагу по всьому коду.

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +    <ul class="footer-social-list">
class="social-list list", не забуваємо вішати клас list на ul щоб сховати крапки. Також social-list незалежний від footer, тому по ВЕМ не згадуємо тут про footer. Звернути на це увагу по всьому коду.

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +        <a href="" class="footer-social-list_link">
Так само і з класом link щоб приховати підкреслення: class="social-list__link link". Звернути на це увагу по всьому коду.

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +    <div class="footer-content-wrapper">
class="page-footer__content_wrapper"

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +      <p class="footer-content-wrapper_text">Feel free to contact</p>
class="page-footer__content_text"

2022-10-08 20:23 UTC, MaksoN03 commented on src/partials/footer.html
> +      <a href="tel:+610383766284" class="footer-content-wrapper_link"
class="page-footer__content_link link"

2022-10-09 07:26 UTC, albinayevtushenko commented on src/partials/footer.html
> +      <a href="tel:+610383766284" class="footer-content-wrapper_link"
done

2022-10-09 07:27 UTC, albinayevtushenko commented on src/partials/footer.html
> +      <p class="footer-content-wrapper_text">Feel free to contact</p>
done

2022-10-09 07:27 UTC, albinayevtushenko commented on src/partials/footer.html
> +    <div class="footer-content-wrapper">
done

2022-10-09 07:27 UTC, albinayevtushenko commented on src/partials/footer.html
> +        <a href="" class="footer-social-list_link">
done

2022-10-09 07:28 UTC, albinayevtushenko commented on src/partials/footer.html
> +    <ul class="footer-social-list">
done

2022-10-09 07:28 UTC, albinayevtushenko commented on src/partials/footer.html
> +    <h2 class="page-footer_title">Homemade ice cream made</h2>
done

2022-10-09 21:25 UTC, albinayevtushenko commented on src/partials/footer.html
> +    <h2 class="page-footer_title">Homemade ice cream made</h2>
done

2022-10-11 20:12 UTC, MaksoN03 approved these changes

2022-10-11 20:17 UTC, MaksoN03 approved these changes

2022-10-11 20:17 UTC, merged