Customer reviews html and css done
MaksoN03/team-project pull request #8
Opened 2022-10-08 18:00 UTC by vrexvf5

2022-10-08 20:34 UTC, MaksoN03 requested changes
Прохання виправити посилання на фотографії як зазначено в коментарі. Також додайте section. Свгшки закиньте в загальний спрайт.

2022-10-08 20:34 UTC, MaksoN03 commented on src/partials/customer-reviews.html
> +<!-- CUSTOMER REVIEWS -->
Прохання додати тег section

2022-10-08 20:34 UTC, MaksoN03 commented on src/partials/customer-reviews.html
> +                    srcset="../images/cr_customer_emily.webp 1x, ../images/cr_customer_emily@2x.webp 2x"
По всіх посиланнях на картинки прибрати подвійні точки, це ламає зборщик. Необхідно залишити одну, наприклад: "./images/cr_customer_emily.webp 1x, ./images/cr_customer_emily@2x.webp 2x"

2022-10-09 14:01 UTC, vrexvf5 commented on src/partials/customer-reviews.html
> +<!-- CUSTOMER REVIEWS -->
Додав

2022-10-09 14:02 UTC, vrexvf5 commented on src/partials/customer-reviews.html
> +                    srcset="../images/cr_customer_emily.webp 1x, ../images/cr_customer_emily@2x.webp 2x"
Виправив

2022-10-09 14:09 UTC, MaksoN03 approved these changes

2022-10-09 14:09 UTC, merged